proxy:
    work: ENC[AES256_GCM,data:EXPbDTXD7kXzi0nuzUfoG0fc+VDFNtY8hpRpN55nQgfI,iv:UsLwIHwJRbF2BRPEIHsGom2SCI+CERY8EFuECvZc6B0=,tag:3NSgPsRWcK+q4IF1j5FCfA==,type:str]
    clash: ENC[AES256_GCM,data:2yC5b3OanUsG3rdpRDdzBscEMKbYug/HFg==,iv:bl47aSqR8JpUhfSxdCTQ25vQVCnpwSPJd8NGZsPwLm0=,tag:HAeHwEKptMHhgGERqITuQw==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:JG660/zxGZQaV57FsXyrTaoFENg1XkQnvLn5qEYc4NyxgOrE8yED9zVcglV06pkhmBTJCdadgqQSBr/rPL+k4zQfHSQqNtnQd2JVv88eoEw=,iv:3BmK7gDa0AVC6SVEZqRBB19UYsOB+cODKRsivORlve8=,tag:g3CTZSlg/g7QSeAm1cB2fQ==,type:str]
atuin_key: ENC[AES256_GCM,data:ot7qAVZYJI/yUMY9ViObpvUZb1xqVIK8+C2UXS2K42RYh2dVbW06xBygwOp2hgoY,iv:LjQAXNQbUALlvxuNGcQYmZjiSv1HIsw8v2SRvg7REDc=,tag:o12XMAu9ZYiEsEfqnF1R/A==,type:str]
git_allowed_signers: ENC[AES256_GCM,data:0olXVHMT5OEPFw9g++52/E74U8WIo5D9wo7SDq2cKIDzzsyLvITMNoHNcYNXCHgpHZBFjar/qL8+cIOmsT8YBg14d6rjZA4rUG7j7u4FxsEgPYEF4F9cTaZ/Q2FBZHBzSrE=,iv:shS8ER/Ax6HuaKdMlVTe5VoeDAKYAlgHJ+jmpfrtCRU=,tag:S4T5y37ZiSntswFt69TC7A==,type:str]
cachix-agent-token: ENC[AES256_GCM,data:8G0NefVRFgKFOZYbMEju499iklzvhuRvZi2R/gl4WXwmnKbfw44NVgsCmhIZuPAPxSgQ78J8phVzBYK9gD/LshEnWT7vGKBCEb22jfcM+2s9DrdQKH6wqWxFxfFG1vK4ZuhM+eEkSBLTvSket6gUz6Xz+X0ao5lefB6Bzjgntz+e42UZmmtNwBbr2vBHYqbYDDBdtTg=,iv:422AN0qj1FXwdC8SCcnxd7v2rhMfY9VO6MA0txIDf/w=,tag:Ernma+0ZEo8wc7tSLdtvoA==,type:str]
sops:
    age:
        - recipient: age1y3dqhzvktelejlv9730d0l0s5h656dzdwv8mu490wgemge20kcgq50dw5w
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcEdEb0RhOEtCc0Z4WGFt
            bWw4M3Q2SW9lRytwQzFXeEx4MTFURW1YTHhFCmVYaU81d2NObFpRem53Tk04eTFI
            aE5LWlFNZmVITGZJL0N4cHZDZjJRY1UKLS0tIE9ZNExENHBPU28reDdrNnl1ZTdE
            VEd0RE9OQnV4N0dOalYxRHlIZzVkMW8KlCjF1YYulwXtsl6qFB0zYW+cR751k1Iq
            4x02tA2nvG2eFdJ+soQPfngiUQAqLi3slSMAdzbLXyuPdko+8mVaAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age15meyx2lnegjd0rgzzg4k7yv3m45yl9jurfq6p2mssh2vzkkhmdlqsepnvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIdnlxQ1I1VGs3T3ZyVDVQ
            WjBXYVpmRDJ5ZHloYXNtTllYdzlqTjFoV2ljCnZaWHNLVi9FQjkyUGR4cDNvWGxp
            YVQ2bEwzYnhHMjFMTHNKYzA4RVZWc28KLS0tIGZlT2ZkSzB1NnFCWUpMdE5BZGx4
            VkU1WnZseXJXaGIwWGd2eXBnYTcva1kK40A3DSBn2KOFzbCfMcVIxOXSGrFs2BfT
            /Iwk3maQjICfG0vcJ2ljimP8pbf3pmUMg2RZe0/bZYuiWx8j2FuJUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T07:16:26Z"
    mac: ENC[AES256_GCM,data:SvcdFAO3wgZCvl22UVsDZD0XN9LVHXyHyONCZODH1NkGOJdsIA/zjmo8+CE4XUzHisoqKoJI0Zrw7LADCdaBUo+0lo6tepSzMpXl8OVGJs5GOEzvsu0PMxCYeBVZR0kKYTzzK4U+B62Zhw8G7yEI8rjRJKyCtcnzCUVvBdj2G8Y=,iv:ksSDvzJKROjTDdiGJbl1+iT7llHq/W+w1yeqtZARcdk=,tag:Tx7kj9IswsC1amIfF53aew==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
