{
  lib,
  pkgs,
  ...
}:
let
  sharedAgentInstructions = import ../agent-instructions { inherit lib pkgs; };
  banner = ''
    <!-- Generated by home-manager from shell-config/home-manager/programs/pi/.
         Edit the Nix source instead of this file. -->
  '';
in
{
  programs.pi-coding-agent = {
    enable = true;
    package = pkgs.unstable.pi-coding-agent;
    extraPackages = with pkgs; [
      nodejs
      bun
    ];

    context = banner + "\n# User-scope Pi Configuration\n\n" + sharedAgentInstructions.text;

    keybindings = {
      "tui.editor.cursorUp" = [
        "up"
        "ctrl+p"
      ];
      "tui.editor.cursorDown" = [
        "down"
        "ctrl+n"
      ];
      # ctrl+p stays bound to app.model.cycleForward by default; app actions
      # are matched before editor bindings, so move model cycling to alt+p.
      "app.model.cycleForward" = [ "alt+p" ];
      "tui.select.up" = [
        "up"
        "ctrl+p"
      ];
      "tui.select.down" = [
        "down"
        "ctrl+n"
      ];
      # Moved off ctrl+p/ctrl+n so they don't shadow tui.select.* in selectors.
      "app.session.togglePath" = [ "alt+shift+p" ];
      "app.session.toggleNamedFilter" = [ "alt+n" ];
      "app.models.toggleProvider" = [ "alt+shift+t" ];
      # thinking.cycle registers before thinking.toggle and first match wins, so
      # it has to vacate shift+tab rather than just sharing it.
      "app.thinking.cycle" = [ "alt+t" ];
      "app.thinking.toggle" = [
        "shift+tab"
        "ctrl+t"
      ];
    };
  };
}
