# Auto-generated using compose2nix v0.3.2-pre, then edited.
{ pkgs, lib, config, ... }:
let
  # Keeps volumes, the mount-ready gate and RequiresMountsFor in sync.
  mountsDir = "/home/chin39/mounts";
  mediaDir = "/mnt/data/Video/jellyfin";
  # networking.proxy.* in vm-nix/default.nix.
  proxy = config.networking.proxy.default;
  noProxy = config.networking.proxy.noProxy;
  jellyfinCjkFonts = pkgs.symlinkJoin {
    name = "jellyfin-cjk-fonts";
    paths = [
      pkgs.noto-fonts-cjk-sans
      pkgs.noto-fonts-cjk-serif
    ];
  };
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune = {
      enable = true;
      dates = "weekly";
      flags = [
        "--all"
        "--filter"
        "until=720h"
      ];
    };
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "jellyfin/jellyfin:${pkgs.jellyfin.version}";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Shanghai";
    } // lib.optionalAttrs (proxy != null) {
      "http_proxy" = proxy;
      "https_proxy" = proxy;
    } // lib.optionalAttrs (noProxy != null) {
      "no_proxy" = noProxy;
    };
    volumes = [
      "/home/chin39/Documents/container/jellyfin/cache:/cache:rw"
      "/home/chin39/Documents/container/jellyfin/config-jellyfin:/config:rw"
      "${jellyfinCjkFonts}/share/fonts/opentype/noto-cjk:/config/fonts:ro"
      # rslave: a remount on the host (rclone restart) propagates into the
      # running container; rprivate would pin the dead FUSE mount instead.
      "${mountsDir}:/mounts:rw,rslave"
      "${mediaDir}:/jellyfin-media:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
      "--health-cmd=bash -c '</dev/tcp/127.0.0.1/8096'"
      "--health-interval=30s"
      "--health-timeout=5s"
      "--health-retries=3"
      "--health-start-period=60s"
    ];
  };
  systemd.services."jellyfin-mount-ready" = {
    description = "Wait for the alist FUSE mount to be ready";
    path = [
      pkgs.coreutils
      pkgs.util-linux
    ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      # Retry until the mount is up: systemd never retries a dependency
      # failure, so a single failed run would block docker-jellyfin for good.
      Restart = "on-failure";
      RestartSec = "15s";
      StartLimitIntervalSec = "0";
    };
    script = ''
      set -eu
      m=${mountsDir}/alist
      mountpoint -q "$m" && [ -n "$(ls -A "$m" 2>/dev/null | head -n1)" ]
      # Boot race: a failed gate cancels docker-jellyfin's start job for good,
      # leaving it inactive (not failed), so no state check is reliable.
      # Unconditional start recovers it; no-op if already running or queued.
      systemctl --no-block start docker-jellyfin.service
    '';
  };

  systemd.services."docker-jellyfin" = {
    unitConfig = {
      # Implies Requires/After on mnt-data.mount.
      RequiresMountsFor = [ mediaDir ];
      StartLimitIntervalSec = "10min";
      StartLimitBurst = 5;
    };
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = "10s";
    };
    after = [
      "docker-network-jellyfin_default.service"
      "jellyfin-mount-ready.service"
    ];
    requires = [
      "docker-network-jellyfin_default.service"
      "jellyfin-mount-ready.service"
    ];
    partOf = [ "docker-compose-jellyfin-root.target" ];
  };

  # Networks
  systemd.services."docker-network-jellyfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "/usr/bin/env docker network rm -f jellyfin_default";
    };
    script = ''
      docker network create jellyfin_default || docker network inspect jellyfin_default
    '';
    partOf = [ "docker-compose-jellyfin-root.target" ];
    wantedBy = [
      "docker-compose-jellyfin-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}
