# Auto-generated using compose2nix v0.3.2-pre, then edited.
{ pkgs, lib, ... }:
let
  jellyfinCjkFonts = pkgs.symlinkJoin {
    name = "jellyfin-cjk-fonts";
    paths = [
      pkgs.noto-fonts-cjk-sans
      pkgs.noto-fonts-cjk-serif
    ];
  };
in
{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune = {
      enable = true;
      dates = "weekly";
      flags = [ "--all" "--filter" "until=720h" ];
    };
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "jellyfin/jellyfin:${pkgs.jellyfin.version}";
    environment = {
      "PGID" = "100";
      "PUID" = "1000";
      "TZ" = "Asia/Shanghai";
      "http_proxy" = "http://192.168.0.240:10809";
      "https_proxy" = "http://192.168.0.240:10809";
    };
    volumes = [
      "/home/chin39/Documents/container/jellyfin/cache:/cache:rw"
      "/home/chin39/Documents/container/jellyfin/config-jellyfin:/config:rw"
      "${jellyfinCjkFonts}/share/fonts/opentype/noto-cjk:/config/fonts:ro"
      "/home/chin39/mounts:/mounts:rw"
      "/mnt/data/video/jellyfin:/jellyfin-media:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
      "--health-cmd=bash -c '</dev/tcp/127.0.0.1/8096'"
      "--health-interval=30s"
      "--health-timeout=5s"
      "--health-retries=3"
      "--health-start-period=60s"
    ];
  };
  systemd.services."jellyfin-mount-ready" = {
    description = "Wait for user-scope rclone FUSE mounts to be ready";
    path = [ pkgs.coreutils pkgs.util-linux ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      TimeoutStartSec = "180";
    };
    script = ''
      set -eu
      deadline=$(( $(date +%s) + 120 ))
      for m in /home/chin39/mounts/{alist,115-single,union-115}; do
        while ! ( mountpoint -q "$m" \
                  && [ -n "$(ls -A "$m" 2>/dev/null | head -n1)" ] ); do
          if [ "$(date +%s)" -gt "$deadline" ]; then
            echo "timeout waiting for $m" >&2
            exit 1
          fi
          sleep 2
        done
      done
    '';
  };

  systemd.services."docker-jellyfin" = {
    unitConfig = {
      RequiresMountsFor = [ "/mnt/data/video/jellyfin" ];
      StartLimitIntervalSec = "10min";
      StartLimitBurst = 5;
    };
    serviceConfig = {
      Restart = lib.mkOverride 90 "on-failure";
      RestartSec = "10s";
    };
    after = [
      "docker-network-jellyfin_default.service"
      "jellyfin-mount-ready.service"
      "mnt-data.mount"
    ];
    requires = [
      "docker-network-jellyfin_default.service"
      "jellyfin-mount-ready.service"
      "mnt-data.mount"
    ];
    partOf = [ "docker-compose-jellyfin-root.target" ];
  };

  # Networks
  systemd.services."docker-network-jellyfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "/usr/bin/env docker network rm -f jellyfin_default";
    };
    script = ''
      docker network create jellyfin_default || docker network inspect jellyfin_default
    '';
    partOf = [ "docker-compose-jellyfin-root.target" ];
    wantedBy = [
      "docker-compose-jellyfin-root.target"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}
