proxy:
    work: ENC[AES256_GCM,data:EXPbDTXD7kXzi0nuzUfoG0fc+VDFNtY8hpRpN55nQgfI,iv:UsLwIHwJRbF2BRPEIHsGom2SCI+CERY8EFuECvZc6B0=,tag:3NSgPsRWcK+q4IF1j5FCfA==,type:str]
    clash: ENC[AES256_GCM,data:mnJ2aHqg6uKWzcCgUq0H+Dv0FZr06lTa6g==,iv:hJwPWMwQzsUhJ6csXn8XsoGD7Nlnzs2mA4WCdBSXRi4=,tag:f/EWJEscrkj21fJpBgPLtg==,type:str]
wg:
    privatekey: ENC[AES256_GCM,data:F5J0muALm7aTQ8FUZash5VUy23QDkz6ueUviwUZGS8V/9aZ98XQ/UM9bSBE=,iv:mfMMWehKjP73Q4qKwamzgMQ0ue6rpDVEq6NmLk2p7bU=,tag:UhOenn1y5AZgVrd/W9IXxA==,type:str]
    pubkey: ENC[AES256_GCM,data:aUzXHroaZhsFsTM+DuzPWeB/uvjL5Ue33+qKICzuykc1G1uDsAh6QmiRVNc=,iv:KE2kZ1iIcWJrT0U2o38UHqeNy5dPJlIYU+HudFf9Dxg=,tag:gT+iw/jKQSmQ7g8/CIQ5nw==,type:str]
    endpoint: ENC[AES256_GCM,data:kOPuu14IMen6TTE4R4nHDHTb5y7ju6I=,iv:RvXUi524mdFb1t6XzddoyoPKvHkZWfe40QuUQR5bUrw=,tag:2uNkKxGdTsTd7blFEagOow==,type:str]
ssh_pub_key: ENC[AES256_GCM,data:rSQU4WT5HeeJsfEUZo+4G0vnozS6m52TmN4hMbH55nbnN+5uCO/5+KqMoQ5wdis4rx07McvQJZUmmO81rYEarRs+vWSuLVOshXpjkS8EvwU=,iv:y7fKAGJ0kWGGpHyLbauro5tnfKU4gk4IuZxlPDewU4I=,tag:FBoKhr12MRPisxXtmp42hg==,type:str]
atuin_key: ENC[AES256_GCM,data:ot7qAVZYJI/yUMY9ViObpvUZb1xqVIK8+C2UXS2K42RYh2dVbW06xBygwOp2hgoY,iv:LjQAXNQbUALlvxuNGcQYmZjiSv1HIsw8v2SRvg7REDc=,tag:o12XMAu9ZYiEsEfqnF1R/A==,type:str]
#ENC[AES256_GCM,data:wEFVMuhBFINgyb2LOBK/,iv:7j89Tn2mlyXUeusgxLmn3KsUJc6KRGpsxEwFCKmlMsI=,tag:cxIr1ihyex74WKB246EIxA==,type:comment]
#ENC[AES256_GCM,data:ZvvK3oQfEh0PidqV5WfiLcV4ul/d,iv:zHGscvLKkwkpxH3Q+veBOAhNKu6tjxRpxTZoEBl/ock=,tag:KZElICQWk82W+4VYd7jY1w==,type:comment]
#ENC[AES256_GCM,data:i14KvPgXa0Z9G6wtfKaH6M06Yks2fcJzAN9a,iv:ItfVv845M4m4Kz6lavJnACrlbzCUlfdAFIIV7I5sw+o=,tag:gKBpcexm1ODBGJ07x9+thA==,type:comment]
#ENC[AES256_GCM,data:5nPmsNDNRYiwetir0aHYtb3j,iv:0BqZFBvrDcDATtTYwBshsgc0nF6ExpettIzyzI9gfNo=,tag:aUbDIZD/DExSy15QDOGaSQ==,type:comment]
#ENC[AES256_GCM,data:xGQVDUh8ibN802M=,iv:yTpVt2503X0XXy1m47geOJgRoNm6ROtn/c6v2MMCNKI=,tag:r2SmjU4qrevFLgsoG5+N1A==,type:comment]
#ENC[AES256_GCM,data:LZDJU5XTSRFvgEyH,iv:3Q9cQDCXqFR7WT+yIk90d0xnCD3/OYarasp6FjXLfKg=,tag:2H7TGFUhJxgf2Mb0xPbwqw==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15meyx2lnegjd0rgzzg4k7yv3m45yl9jurfq6p2mssh2vzkkhmdlqsepnvr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjY1U2VUVQeWpETk0yVmJq
            RDVDejd4T0FFckZuQ3pIY1NOU2p1amhPOXlvCjJ4MTVodm03cCtidDlvMG1VZ1NU
            RXB3amFqKzVXOS80ZHRjMkQyY0E2WXMKLS0tIDhXdGR4dkZtSkVVMGhyUDU0eTds
            V1VZK3p5bUhmRTJJelY4K0RiZFBOTGcK0nf4vVLp0pGrwhbveWHKZ+Nn10PWmEYw
            ldJh49AHFS0PVr68vibHBsoXGo/ZHhQ4QheT7qcmsIL2oC0gGcsxyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-17T15:19:42Z"
    mac: ENC[AES256_GCM,data:cHBdBna+TuTuFfkme0MwcRF0oWLfiwDmeULs+/Hg5DwVa3ak01izZq+zIFUOiv+CC4mqmhg5RclgoDWUbIMUTfkN2WhvKJ22cwm6kXipy62oWc99CM5LnCL/mYLkxSyI3rsu6LhSF+EH84zmRwcZui4s+1p/zoUIKCOVrCKHv00=,iv:Mb95siTYiKjpfWkDga6YXC0V2JA2QZFVqU1YNCOjYfU=,tag:rKKbEgONy0yCAo6i1dMjVg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
